"""
Translates name of attribute in XML validation report Entry element to a name of property
in ProteinDataFromXML. Only the float values.
"""
XML_ENTRY_ATTRIBUTE_TO_PROPERTY = {
    "clashscore": "clashscore",
    "percent-rama-outliers": "percent_rama_outliers",
    "percent-rota-outliers": "percent_rota_outliers",
    "absolute-percentile-clashscore": "absolute_percentile_clashscore",
    "relative-percentile-clashscore": "relative_percentile_clashscore",
    "numPDBids-relative-percentile-clashscore": "num_pdb_ids_relative_percentile_clashscore",
    "low-resol-relative-percentile-clashscore": "low_resol_relative_percentile_clashscore",
    "high-resol-relative-percentile-clashscore": "high_resol_relative_percentile_clashscore",
    "absolute-percentile-percent-rama-outliers": "absolute_percentile_percent_rama_outliers",
    "relative-percentile-percent-rama-outliers": "relative_percentile_percent_rama_outliers",
    "numPDBids-relative-percentile-percent-rama-outliers": "num_pdb_ids_relative_percentile_percent_rama_outliers",
    "low-resol-relative-percentile-percent-rama-outliers": "low_resol_relative_percentile_percent_rama_outliers",
    "high-resol-relative-percentile-percent-rama-outliers": "high_resol_relative_percentile_percent_rama_outliers",
    "absolute-percentile-percent-rota-outliers": "absolute_percentile_percent_rota_outliers",
    "relative-percentile-percent-rota-outliers": "relative_percentile_percent_rota_outliers",
    "numPDBids-relative-percentile-percent-rota-outliers": "num_pdb_ids_relative_percentile_percent_rota_outliers",
    "low-resol-relative-percentile-percent-rota-outliers": "low_resol_relative_percentile_percent_rota_outliers",
    "high-resol-relative-percentile-percent-rota-outliers": "high_resol_relative_percentile_percent_rota_outliers",
    "angles_rmsz": "angles_rmsz",
    "bonds_rmsz": "bonds_rmsz",
    "percent-RSRZ-outliers": "percent_rsrz_outliers",
    "absolute-percentile-percent-RSRZ-outliers": "absolute_percentile_percent_rsrz_outliers",
    "relative-percentile-percent-RSRZ-outliers": "relative_percentile_percent_rsrz_outliers",
    "numPDBids-relative-percentile-percent-RSRZ-outliers": "num_pdb_ids_realtive_percentile_percent_rsrz_outliers",
    "low-resol-relative-percentile-percent-RSRZ-outliers": "low_resol_relative_percentile_percent_rsrz_outliers",
    "high-resol-relative-percentile-percent-RSRZ-outliers": "high_resol_relative_percentile_percent_rsrz_outliers",
    "DCC_R": "dcc_r",
    "DCC_Rfree": "dcc_r_free",
    "absolute-percentile-DCC_Rfree": "absolute_percentile_dcc_r_free",
    "relative-percentile-DCC_Rfree": "relative_percentile_dcc_r_free",
    "numPDBids-relative-percentile-DCC_Rfree": "num_pdb_ids_relative_percentile_dcc_r_free",
    "low-resol-relative-percentile-DCC_Rfree": "low_resolution_relative_percentile_dcc_r_free",
    "high-resol-relative-percentile-DCC_Rfree": "high_resolution_relative_percentile_dcc_r_free",
    "absolute-percentile-RNAsuiteness": "absolute_percentile_rna_suiteness",
}
