from src.models.factor_type import FactorType


CSV_INVALID_VALUE_STRING = "nan"


"""
Translates property name of protein data into the name it will have in the final csv.
The keys need to be exact name of properties of protein data classes, the values are the name of the column
in resulting CSV. Be mindful of it when editing.
"""
CSV_OUTPUT_ATTRIBUTE_NAMES = {
    "angles_rmsz": FactorType.ANGLE_RMSZ_STRUCTURE,
    "assembly_biopolymer_count": FactorType.ASSEMBLY_BIOPOLYMER_COUNT,
    "assembly_biopolymer_weight_kda": FactorType.ASSEMBLY_BIOPOLYMER_WEIGHT,
    "assembly_ligand_count": FactorType.ASSEMBLY_LIGAND_COUNT,
    "assembly_ligand_flexibility": FactorType.ASSEMBLY_LIGAND_FLEXIBILITY,
    "assembly_ligand_weight_da": FactorType.ASSEMBLY_LIGAND_WEIGHT,
    "molecular_weight": FactorType.ASSEMBLY_TOTAL_WEIGHT,
    "assembly_unique_biopolymer_count": FactorType.ASSEMBLY_UNIQUE_BIOPOLYMER_COUNT,
    "assembly_unique_ligand_count": FactorType.ASSEMBLY_UNIQUE_LIGAND_COUNT,
    "assembly_water_count": FactorType.ASSEMBLY_WATER_COUNT,
    "assembly_water_weight_da": FactorType.ASSEMBLY_WATER_WEIGHT,
    "bonds_rmsz": FactorType.BOND_RMSZ_STRUCTURE,
    "chira_problems_precise": FactorType.CHIRA_PROBLEMS_PRECISE,
    "chira_problems_precise_binary": FactorType.CHIRA_PROBLEMS_PRECISE_BINARY,
    "ligand_quality_ratio_bad_chirality_carbon": FactorType.CHIRAL_PROBLEM_LIGAND_RATIO,
    "absolute_percentile_clashscore": FactorType.CLASHSCORE_PERCENTILE,
    "relative_percentile_clashscore": FactorType.CLASHSCORE_RELATIVE_PERCENTILE,
    "num_pdb_ids_relative_percentile_clashscore": FactorType.CLASHSCORE_RELATIVE_PERCENTILE_COUNT,
    "high_resol_relative_percentile_clashscore": FactorType.CLASHSCORE_RELATIVE_PERCENTILE_MAX_RESOLUTION,
    "low_resol_relative_percentile_clashscore": FactorType.CLASHSCORE_RELATIVE_PERCENTILE_MIN_RESOLUTION,
    "dcc_r": FactorType.DCC_R,
    "dcc_r_free": FactorType.DCC_R_FREE,
    "absolute_percentile_dcc_r_free": FactorType.DCC_R_PERCENTILE,
    "relative_percentile_dcc_r_free": FactorType.DCC_R_RELATIVE_PERCENTILE,
    "num_pdb_ids_relative_percentile_dcc_r_free": FactorType.DCC_R_RELATIVE_PERCENTILE_COUNT,
    "high_resolution_relative_percentile_dcc_r_free": FactorType.DCC_R_RELATIVE_PERCENTILE_MAX_RESOLUTION,
    "low_resolution_relative_percentile_dcc_r_free": FactorType.DCC_R_RELATIVE_PERCENTILE_MIN_RESOLUTION,
    "ligand_quality_ratio_good_chirality_carbon": FactorType.GOOD_LIGAND_RATIO,
    "ligand_quality_binary_good_chirality_carbon": FactorType.GOOD_LIGAND_RATIO_BINARY,
    "missing_carbon_chira_errors_precise": FactorType.LIGAND_TOPOLOGY_CARBON_CHIRA_PROBLEMS_PRECISE,
    "ligand_quality_binary_missing_atoms_and_rings": FactorType.LIGAND_TOPOLOGY_CARBON_CHIRA_PROBLEMS_PRECISE_BINARY,
    "missing_precise": FactorType.LIGAND_TOPOLOGY_PROBLEMS_PRECISE,
    "missing_precise_binary": FactorType.LIGAND_TOPOLOGY_PROBLEMS_PRECISE_BINARY,
    "nonpolymer_weight_da": FactorType.NONPOLYMER_WEIGHT,
    "nonpolymer_weight_no_water_da": FactorType.NONPOLYMER_WEIGHT_NOWATER,
    "pdb_id": FactorType.PDB_ID,
    "polymer_weight_kda": FactorType.POLYMER_WEIGHT,
    "percent_rsrz_outliers": FactorType.RSRZ_OUTLIERS,
    "absolute_percentile_percent_rsrz_outliers": FactorType.RSRZ_OUTLIERS_PERCENTILE,
    "relative_percentile_percent_rsrz_outliers": FactorType.RSRZ_OUTLIERS_RELATIVE_PERCENTILE,
    "num_pdb_ids_realtive_percentile_percent_rsrz_outliers": FactorType.RSRZ_OUTLIERS_RELATIVE_PERCENTILE_COUNT,
    "high_resol_relative_percentile_percent_rsrz_outliers": FactorType.RSRZ_OUTLIERS_RELATIVE_PERCENTILE_MAX_RESOLUTION,
    "low_resol_relative_percentile_percent_rsrz_outliers": FactorType.RSRZ_OUTLIERS_RELATIVE_PERCENTILE_MIN_RESOLUTION,
    "percent_rama_outliers": FactorType.RAMA_OUTLIERS,
    "absolute_percentile_percent_rama_outliers": FactorType.RAMA_OUTLIERS_PERCENTILE,
    "relative_percentile_percent_rama_outliers": FactorType.RAMA_OUTLIERS_RELATIVE_PERCENTILE,
    "num_pdb_ids_relative_percentile_percent_rama_outliers": FactorType.RAMA_OUTLIERS_RELATIVE_PERCENTILE_COUNT,
    "high_resol_relative_percentile_percent_rama_outliers": FactorType.RAMA_OUTLIERS_RELATIVE_PERCENTILE_MAX_RESOLUTION,
    "low_resol_relative_percentile_percent_rama_outliers": FactorType.RAMA_OUTLIERS_RELATIVE_PERCENTILE_MIN_RESOLUTION,
    "percent_rota_outliers": FactorType.SIDECHAIN_OUTLIERS,
    "absolute_percentile_percent_rota_outliers": FactorType.SIDECHAIN_OUTLIERS_PERCENTILE,
    "relative_percentile_percent_rota_outliers": FactorType.SIDECHAIN_OUTLIERS_RELATIVE_PERCENTILE,
    "num_pdb_ids_relative_percentile_percent_rota_outliers": FactorType.SIDECHAIN_OUTLIERS_RELATIVE_PERCENTILE_COUNT,
    "high_resol_relative_percentile_percent_rota_outliers": FactorType.SIDECHAIN_OUTLIERS_RELATIVE_PERCENTILE_MAX_RESOLUTION,
    "low_resol_relative_percentile_percent_rota_outliers": FactorType.SIDECHAIN_OUTLIERS_RELATIVE_PERCENTILE_MIN_RESOLUTION,
    "structure_weight_kda": FactorType.STRUCTURE_WEIGHT,
    "ligand_quality_missing_atoms_and_rings": FactorType.TOPOLOGY_PROBLEM_LIGAND_RATIO,
    "water_weight_da": FactorType.WATER_WEIGHT,
    "aa_count": FactorType.AA_COUNT,
    "aa_ligand_count": FactorType.AA_LIGAND_COUNT,
    "aa_ligand_count_filtered": FactorType.AA_LIGAND_COUNT_FILTERED,
    "aa_ligand_count_no_water": FactorType.AA_LIGAND_COUNT_NOWATER,
    "absolute_percentile_rna_suiteness": FactorType.ABSOLUTE_PERCENTILE_RNA_SUITENESS,
    "all_atom_count": FactorType.ALL_ATOM_COUNT,
    "all_atom_count_ln": FactorType.ALL_ATOM_COUNT_LN,
    "atom_count_without_hetatms": FactorType.ATOM_COUNT,
    "average_ligand_angle_rmsz": FactorType.AVERAGE_LIGAND_ANGLE_RMSZ,
    "average_ligand_bond_rmsz": FactorType.AVERAGE_LIGAND_BOND_RMSZ,
    "average_ligand_rscc": FactorType.AVERAGE_LIGAND_RSCC,
    "average_ligand_rscc_large_ligands": FactorType.AVERAGE_LIGAND_RSCC_LARGE_LIGS,
    "average_ligand_rscc_small_ligands": FactorType.AVERAGE_LIGAND_RSCC_SMALL_LIGS,
    "average_ligand_rsr": FactorType.AVERAGE_LIGAND_RSR,
    "average_residue_rscc": FactorType.AVERAGE_RESIDUE_RSCC,
    "average_residue_rsr": FactorType.AVERAGE_RESIDUE_RSR,
    "clashscore": FactorType.CLASHSCORE,
    "combined_geometry_quality": FactorType.COMBINED_GEOMETRY_QUALITY,
    "combined_overall_quality_metric": FactorType.COMBINED_OVERALL_QUALITY_METRIC,
    "combined_x_ray_quality_metric": FactorType.COMBINED_XRAY_QUALITY_METRIC,
    "experimental_method": FactorType.EXPERIMENTAL_METHOD,
    "hetatm_count": FactorType.HETATM_COUNT,
    "hetatm_count_filtered": FactorType.HETATM_COUNT_FILTERED,
    "hetatm_count_filtered_metal": FactorType.HETATM_COUNT_FILTERED_METAL,
    "hetatm_count_filtered_no_metal": FactorType.HETATM_COUNT_FILTERED_NOMETAL,
    "hetatm_count_metal": FactorType.HETATM_COUNT_METAL,
    "hetatm_count_no_metal": FactorType.HETATM_COUNT_NOMETAL,
    "hetatm_count_no_water": FactorType.HETATM_COUNT_NOWATER,
    "hetatm_count_no_water_no_metal": FactorType.HETATM_COUNT_NOWATER_NOMETAL,
    "highest_chain_angles_rmsz": FactorType.HIGHEST_CHAIN_ANGLES_RMSZ,
    "highest_chain_bonds_rmsz": FactorType.HIGHEST_CHAIN_BONDS_RMSZ,
    "ligand_bond_rotation_freedom": FactorType.LIGAND_BOND_ROTATION_FREEDOM,
    "ligand_carbon_chira_atom_count_filtered": FactorType.LIGAND_CARBON_CHIRA_ATOM_COUNT_FILTERED,
    "ligand_count": FactorType.LIGAND_COUNT,
    "ligand_count_filtered": FactorType.LIGAND_COUNT_FILTERED,
    "ligand_count_filtered_metal": FactorType.LIGAND_COUNT_FILTERED_METAL,
    "ligand_count_filtered_no_metal": FactorType.LIGAND_COUNT_FILTERED_NOMETAL,
    "ligand_count_metal": FactorType.LIGAND_COUNT_METAL,
    "ligand_count_no_metal": FactorType.LIGAND_COUNT_NOMETAL,
    "ligand_count_no_water": FactorType.LIGAND_COUNT_NOWATER,
    "ligand_count_no_water_no_metal": FactorType.LIGAND_COUNT_NOWATER_NOMETAL,
    "ligand_rscc_outlier_ratio": FactorType.LIGAND_RSCC_OUTLIER_RATIO,
    "ligand_ratio": FactorType.LIGAND_RATIO,
    "ligand_ratio_filtered": FactorType.LIGAND_RATIO_FILTERED,
    "ligand_ratio_filtered_metal": FactorType.LIGAND_RATIO_FILTERED_METAL,
    "ligand_ratio_filtered_no_metal": FactorType.LIGAND_RATIO_FILTERED_NOMETAL,
    "ligand_ratio_metal": FactorType.LIGAND_RATIO_METAL,
    "ligand_ratio_no_metal": FactorType.LIGAND_RATIO_NOMETAL,
    "ligand_ratio_no_water": FactorType.LIGAND_RATIO_NOWATER,
    "ligand_ratio_no_water_no_metal": FactorType.LIGAND_RATIO_NOWATER_NOMETAL,
    "release_date": FactorType.RELEASE_DATE,
    "residue_rscc_outlier_ratio": FactorType.RESIDUE_RSCC_OUTLIER_RATIO,
    "resolution": FactorType.RESOLUTION,
}

"""
Order of columns in the resulting crunched csv.
"""
CRUNCHED_CSV_FACTOR_TYPES_ORDER = [
    FactorType.PDB_ID,
    FactorType.RESOLUTION,
    FactorType.RELEASE_DATE,
    FactorType.STRUCTURE_WEIGHT,
    FactorType.POLYMER_WEIGHT,
    FactorType.NONPOLYMER_WEIGHT,
    FactorType.NONPOLYMER_WEIGHT_NOWATER,
    FactorType.WATER_WEIGHT,
    FactorType.ATOM_COUNT,
    FactorType.HETATM_COUNT,
    FactorType.ALL_ATOM_COUNT,
    FactorType.ALL_ATOM_COUNT_LN,
    FactorType.AA_COUNT,
    FactorType.LIGAND_COUNT,
    FactorType.LIGAND_BOND_ROTATION_FREEDOM,
    FactorType.AA_LIGAND_COUNT,
    FactorType.AA_LIGAND_COUNT_NOWATER,
    FactorType.AA_LIGAND_COUNT_FILTERED,
    FactorType.LIGAND_RATIO,
    FactorType.HETATM_COUNT_NOWATER,
    FactorType.LIGAND_COUNT_NOWATER,
    FactorType.LIGAND_RATIO_NOWATER,
    FactorType.HETATM_COUNT_FILTERED,
    FactorType.LIGAND_CARBON_CHIRA_ATOM_COUNT_FILTERED,
    FactorType.LIGAND_COUNT_FILTERED,
    FactorType.LIGAND_RATIO_FILTERED,
    FactorType.HETATM_COUNT_METAL,
    FactorType.LIGAND_COUNT_METAL,
    FactorType.LIGAND_RATIO_METAL,
    FactorType.HETATM_COUNT_NOMETAL,
    FactorType.LIGAND_COUNT_NOMETAL,
    FactorType.LIGAND_RATIO_NOMETAL,
    FactorType.HETATM_COUNT_NOWATER_NOMETAL,
    FactorType.LIGAND_COUNT_NOWATER_NOMETAL,
    FactorType.LIGAND_RATIO_NOWATER_NOMETAL,
    FactorType.HETATM_COUNT_FILTERED_METAL,
    FactorType.LIGAND_COUNT_FILTERED_METAL,
    FactorType.LIGAND_RATIO_FILTERED_METAL,
    FactorType.HETATM_COUNT_FILTERED_NOMETAL,
    FactorType.LIGAND_COUNT_FILTERED_NOMETAL,
    FactorType.LIGAND_RATIO_FILTERED_NOMETAL,
    FactorType.CLASHSCORE,
    FactorType.RAMA_OUTLIERS,
    FactorType.SIDECHAIN_OUTLIERS,
    FactorType.CLASHSCORE_PERCENTILE,
    FactorType.CLASHSCORE_RELATIVE_PERCENTILE,
    FactorType.CLASHSCORE_RELATIVE_PERCENTILE_COUNT,
    FactorType.CLASHSCORE_RELATIVE_PERCENTILE_MIN_RESOLUTION,
    FactorType.CLASHSCORE_RELATIVE_PERCENTILE_MAX_RESOLUTION,
    FactorType.RAMA_OUTLIERS_PERCENTILE,
    FactorType.RAMA_OUTLIERS_RELATIVE_PERCENTILE,
    FactorType.RAMA_OUTLIERS_RELATIVE_PERCENTILE_COUNT,
    FactorType.RAMA_OUTLIERS_RELATIVE_PERCENTILE_MIN_RESOLUTION,
    FactorType.RAMA_OUTLIERS_RELATIVE_PERCENTILE_MAX_RESOLUTION,
    FactorType.SIDECHAIN_OUTLIERS_PERCENTILE,
    FactorType.SIDECHAIN_OUTLIERS_RELATIVE_PERCENTILE,
    FactorType.SIDECHAIN_OUTLIERS_RELATIVE_PERCENTILE_COUNT,
    FactorType.SIDECHAIN_OUTLIERS_RELATIVE_PERCENTILE_MIN_RESOLUTION,
    FactorType.SIDECHAIN_OUTLIERS_RELATIVE_PERCENTILE_MAX_RESOLUTION,
    FactorType.COMBINED_GEOMETRY_QUALITY,
    FactorType.DCC_R,
    FactorType.DCC_R_FREE,
    FactorType.DCC_R_PERCENTILE,
    FactorType.DCC_R_RELATIVE_PERCENTILE,
    FactorType.DCC_R_RELATIVE_PERCENTILE_COUNT,
    FactorType.DCC_R_RELATIVE_PERCENTILE_MIN_RESOLUTION,
    FactorType.DCC_R_RELATIVE_PERCENTILE_MAX_RESOLUTION,
    FactorType.ANGLE_RMSZ_STRUCTURE,
    FactorType.BOND_RMSZ_STRUCTURE,
    FactorType.RSRZ_OUTLIERS,
    FactorType.RSRZ_OUTLIERS_PERCENTILE,
    FactorType.RSRZ_OUTLIERS_RELATIVE_PERCENTILE,
    FactorType.RSRZ_OUTLIERS_RELATIVE_PERCENTILE_COUNT,
    FactorType.RSRZ_OUTLIERS_RELATIVE_PERCENTILE_MIN_RESOLUTION,
    FactorType.RSRZ_OUTLIERS_RELATIVE_PERCENTILE_MAX_RESOLUTION,
    FactorType.COMBINED_XRAY_QUALITY_METRIC,
    FactorType.COMBINED_OVERALL_QUALITY_METRIC,
    FactorType.HIGHEST_CHAIN_BONDS_RMSZ,
    FactorType.HIGHEST_CHAIN_ANGLES_RMSZ,
    FactorType.AVERAGE_RESIDUE_RSR,
    FactorType.CHIRAL_PROBLEM_LIGAND_RATIO,
    FactorType.GOOD_LIGAND_RATIO,
    FactorType.TOPOLOGY_PROBLEM_LIGAND_RATIO,
    FactorType.LIGAND_TOPOLOGY_PROBLEMS_PRECISE,
    FactorType.LIGAND_TOPOLOGY_CARBON_CHIRA_PROBLEMS_PRECISE,
    FactorType.CHIRA_PROBLEMS_PRECISE,
    FactorType.GOOD_LIGAND_RATIO_BINARY,
    FactorType.LIGAND_TOPOLOGY_PROBLEMS_PRECISE_BINARY,
    FactorType.LIGAND_TOPOLOGY_CARBON_CHIRA_PROBLEMS_PRECISE_BINARY,
    FactorType.CHIRA_PROBLEMS_PRECISE_BINARY,
    FactorType.AVERAGE_LIGAND_RSR,
    FactorType.AVERAGE_LIGAND_ANGLE_RMSZ,
    FactorType.AVERAGE_LIGAND_BOND_RMSZ,
    FactorType.AVERAGE_LIGAND_RSCC,
    FactorType.LIGAND_RSCC_OUTLIER_RATIO,
    FactorType.ASSEMBLY_TOTAL_WEIGHT,
    FactorType.ASSEMBLY_BIOPOLYMER_COUNT,
    FactorType.ASSEMBLY_UNIQUE_BIOPOLYMER_COUNT,
    FactorType.ASSEMBLY_LIGAND_COUNT,
    FactorType.ASSEMBLY_UNIQUE_LIGAND_COUNT,
    FactorType.ASSEMBLY_WATER_COUNT,
    FactorType.ASSEMBLY_BIOPOLYMER_WEIGHT,
    FactorType.ASSEMBLY_LIGAND_WEIGHT,
    FactorType.ASSEMBLY_WATER_WEIGHT,
    FactorType.AVERAGE_RESIDUE_RSCC,
    FactorType.RESIDUE_RSCC_OUTLIER_RATIO,
    FactorType.ASSEMBLY_LIGAND_FLEXIBILITY,
    FactorType.AVERAGE_LIGAND_RSCC_SMALL_LIGS,
    FactorType.AVERAGE_LIGAND_RSCC_LARGE_LIGS,
    FactorType.ABSOLUTE_PERCENTILE_RNA_SUITENESS,
    FactorType.EXPERIMENTAL_METHOD,
]

# translates the types into names for easier handling
CRUNCHED_CSV_FACTOR_ORDER = [factor_type.value for factor_type in CRUNCHED_CSV_FACTOR_TYPES_ORDER]
