CSV_INVALID_VALUE_STRING = "nan"


"""
Translates property name of protein data into the name it will have in the final csv.
"""
CSV_OUTPUT_ATTRIBUTE_NAMES = {
    "angles_rmsz": "AngleRMSZstructure",
    "assembly_biopolymer_count": "AssemblyBiopolymerCount",
    "assembly_biopolymer_weight_kda": "AssemblyBiopolymerWeight",
    "assembly_ligand_count": "AssemblyLigandCount",
    "assembly_ligand_flexibility": "AssemblyLigandFlexibility",
    "assembly_ligand_weight_da": "AssemblyLigandWeight",
    "molecular_weight": "AssemblyTotalWeight",
    "assembly_unique_biopolymer_count": "AssemblyUniqueBiopolymerCount",
    "assembly_unique_ligand_count": "AssemblyUniqueLigandCount",
    "assembly_water_count": "AssemblyWaterCount",
    "assembly_water_weight_da": "AssemblyWaterWeight",
    "bonds_rmsz": "BondRMSZstructure",
    "chira_problems_precise": "ChiraProblemsPrecise",
    # "": "ChiraProblemsPreciseBinary",
    # "": "ChiralProblemLigandRatio",
    "absolute_percentile_clashscore": "ClashscorePercentile",
    "relative_percentile_clashscore": "ClashscoreRelativePercentile",
    "num_pdb_ids_relative_percentile_clashscore": "ClashscoreRelativePercentileCount",
    "high_resol_relative_percentile_clashscore": "ClashscoreRelativePercentileMaxResolution",
    "low_resol_relative_percentile_clashscore": "ClashscoreRelativePercentileMinResolution",
    "dcc_r": "DCC_R",
    "dcc_r_free": "DCC_Rfree",
    "absolute_percentile_dcc_r_free": "DCC_Rpercentile",
    "relative_percentile_dcc_r_free": "DCC_RrelativePercentile",
    "num_pdb_ids_relative_percentile_dcc_r_free": "DCC_RrelativePercentileCount",
    "high_resolution_relative_percentile_dcc_r_free": "DCC_RrelativePercentileMaxResolution",
    "low_resolution_relative_percentile_dcc_r_free": "DCC_RrelativePercentileMinResolution",
    # "": "GoodLigandRatio",
    # "": "GoodLigandRatioBinary",
    # "": "LigandTopologyCarbonChiraProblemsPrecise",
    # "": "LigandTopologyCarbonChiraProblemsPreciseBinary",
    # "": "LigandTopologyProblemsPrecise",
    # "": "LigandTopologyProblemsPreciseBinary",
    "nonpolymer_weight_da": "NonpolymerWeight",
    "nonpolymer_weight_no_water_da": "NonpolymerWeightNowater",
    "pdb_id": "PDB ID",
    "polymer_weight_kda": "PolymerWeight",
    "percent_rsrz_outliers": "RSRZoutliers",
    "absolute_percentile_percent_rsrz_outliers": "RSRZoutliersPercentile",
    "relative_percentile_percent_rsrz_outliers": "RSRZoutliersRelativePercentile",
    "num_pdb_ids_realtive_percentile_percent_rsrz_outliers": "RSRZoutliersRelativePercentileCount",
    "high_resol_relative_percentile_percent_rsrz_outliers": "RSRZoutliersRelativePercentileMaxResolution",
    "low_resol_relative_percentile_percent_rsrz_outliers": "RSRZoutliersRelativePercentileMinResolution",
    "percent_rama_outliers": "RamaOutliers",
    "absolute_percentile_percent_rama_outliers": "RamaOutliersPercentile",
    "relative_percentile_percent_rama_outliers": "RamaOutliersRelativePercentile",
    "num_pdb_ids_relative_percentile_percent_rama_outliers": "RamaOutliersRelativePercentileCount",
    "high_resol_relative_percentile_percent_rama_outliers": "RamaOutliersRelativePercentileMaxResolution",
    "low_resol_relative_percentile_percent_rama_outliers": "RamaOutliersRelativePercentileMinResolution",
    "percent_rota_outliers": "SidechainOutliers",
    "absolute_percentile_percent_rota_outliers": "SidechainOutliersPercentile",
    "relative_percentile_percent_rota_outliers": "SidechainOutliersRelativePercentile",
    "num_pdb_ids_relative_percentile_percent_rota_outliers": "SidechainOutliersRelativePercentileCount",
    "high_resol_relative_percentile_percent_rota_outliers": "SidechainOutliersRelativePercentileMaxResolution",
    "low_resol_relative_percentile_percent_rota_outliers": "SidechainOutliersRelativePercentileMinResolution",
    "structure_weight_kda": "StructureWeight",
    # "": "TopologyProblemLigandRatio",
    "water_weight_da": "WaterWeight",
    "aa_count": "aaCount",
    "aa_ligand_count": "aaLigandCount",
    "aa_ligand_count_filtered": "aaLigandCountFiltered",
    "aa_ligand_count_no_water": "aaLigandCountNowater",
    "absolute_percentile_rna_suiteness": "absolute-percentile-RNAsuiteness",
    "all_atom_count": "allAtomCount",
    "all_atom_count_ln": "allAtomCountLn",
    "atom_count_without_hetatms": "atomCount",
    "average_ligand_angle_rmsz": "averageLigandAngleRMSZ",
    "average_ligand_bond_rmsz": "averageLigandBondRMSZ",
    "average_ligand_rscc": "averageLigandRSCC",
    "average_ligand_rscc_large_ligands": "averageLigandRSCClargeLigs",
    "average_ligand_rscc_small_ligands": "averageLigandRSCCsmallLigs",
    "average_ligand_rsr": "averageLigandRSR",
    "average_residue_rscc": "averageResidueRSCC",
    "average_residue_rsr": "averageResidueRSR",
    "clashscore": "clashscore",
    "combined_geometry_quality": "combinedGeometryQuality",
    "combined_overall_quality_metric": "combinedOverallQualityMetric",
    "combined_x_ray_quality_metric": "combinedXrayQualityMetric",
    # "": "experimentalMethod",
    "hetatm_count": "hetatmCount",
    "hetatm_count_filtered": "hetatmCountFiltered",
    "hetatm_count_filtered_metal": "hetatmCountFilteredMetal",
    "hetatm_count_filtered_no_metal": "hetatmCountFilteredNometal",
    "hetatm_count_metal": "hetatmCountMetal",
    "hetatm_count_no_metal": "hetatmCountNometal",
    "hetatm_count_no_water": "hetatmCountNowater",
    "hetatm_count_no_water_no_metal": "hetatmCountNowaterNometal",
    "highest_chain_angles_rmsz": "highestChainAnglesRMSZ",
    "highest_chain_bonds_rmsz": "highestChainBondsRMSZ",
    "ligand_bond_rotation_freedom": "ligandBondRotationFreedom",
    "ligand_carbon_chira_atom_count_filtered": "ligandCarbonChiraAtomCountFiltered",
    "ligand_count": "ligandCount",
    "ligand_count_filtered": "ligandCountFiltered",
    "ligand_count_filtered_metal": "ligandCountFilteredMetal",
    "ligand_count_filtered_no_metal": "ligandCountFilteredNometal",
    "ligand_count_metal": "ligandCountMetal",
    "ligand_count_no_metal": "ligandCountNometal",
    "ligand_count_no_water": "ligandCountNowater",
    "ligand_count_no_water_no_metal": "ligandCountNowaterNometal",
    "ligand_rscc_outlier_ratio": "ligandRSCCoutlierRatio",
    "ligand_ratio": "ligandRatio",
    "ligand_ratio_filtered": "ligandRatioFiltered",
    "ligand_ratio_filtered_metal": "ligandRatioFilteredMetal",
    "ligand_ratio_filtered_no_metal": "ligandRatioFilteredNometal",
    "ligand_ratio_metal": "ligandRatioMetal",
    "ligand_ratio_no_metal": "ligandRatioNometal",
    "ligand_ratio_no_water": "ligandRatioNowater",
    "ligand_ratio_no_water_no_metal": "ligandRatioNowaterNometal",
    "release_date": "releaseDate",
    "residue_rscc_outlier_ratio": "residueRSCCoutlierRatio",
    "resolution": "resolution",
}


CSV_ATTRIBUTE_ORDER = list(CSV_OUTPUT_ATTRIBUTE_NAMES.values())
